export type Service = {
    slug: string;
    name: string;
    headline: string;
    description: string;
    short: string;
    uses: [
        string,
        string
    ][];
    flow: [
        string,
        string
    ][];
    gate: number;
    gateNote: string;
    outcomes: [
        string,
        string
    ][];
    measures: string[];
    faq: [
        string,
        string
    ][];
};
export const services: Service[] = [
    { slug: 'document-multimodal-intelligence', name: 'Business Operations', headline: 'Less retyping. More work moving.', short: 'Turn documents into checked, usable information.', description: 'Read the documents, check the details and move the work forward. Give your team the exceptions that need their attention, with the evidence already attached.', uses: [['Invoices & purchase orders', 'Extract line items, match records and flag differences before posting.'], ['KYC & onboarding', 'Check completeness and route missing or unclear information for review.'], ['Logistics documents', 'Connect proof of delivery, shipment records and claims.'], ['Contracts & RFQs', 'Find the fields and clauses your team needs to review.']], flow: [['Receive', 'Email, upload or connected inbox'], ['Read', 'Extract fields with their source'], ['Check', 'Match your rules and records'], ['Review', 'A person resolves exceptions'], ['Post', 'Update the approved destination']], gate: 3, gateNote: 'Unclear fields and policy exceptions go to a named reviewer.', outcomes: [['Less repeated entry', 'A checked record moves between your tools.'], ['Clearer exceptions', 'Review the issue with the original document beside it.'], ['A traceable process', 'Follow what arrived, what changed and who approved it.']], measures: ['Time per document', 'Error and rework rate', 'Share needing review', 'Cost per completed record'], faq: [['Can it work with our existing documents?', 'We test representative examples first, including poor scans and different layouts. The Blueprint identifies which formats are suitable and where review remains necessary.'], ['Does every document need approval?', 'You choose the rules. Routine cases can proceed within agreed limits; uncertain fields and exceptions wait for a reviewer.'], ['Which tools can it connect to?', 'We assess your accounting, ERP, storage and internal APIs during scoping. Access and supported interfaces determine the integration.']] },
    { slug: 'agentic-operations', name: 'Agentic Operations', headline: 'Move the work. Keep the control.', short: 'Carry multi-step work across teams and tools.', description: 'Give recurring work a clear path from request to resolution. Bounded agents gather context, use permitted tools and hand consequential decisions to your team.', uses: [['Customer onboarding', 'Coordinate checks, tasks and handoffs across the business.'], ['Order-to-cash', 'Prepare the next action with the order and account context.'], ['Reconciliation', 'Investigate differences and package the evidence.'], ['Internal requests', 'Route work, follow up and keep owners informed.']], flow: [['Trigger', 'A request or event arrives'], ['Plan', 'Choose the permitted next steps'], ['Prepare', 'Gather evidence and draft action'], ['Approve', 'Review consequential actions'], ['Act & log', 'Run the approved action and record it']], gate: 3, gateNote: 'Money, commitments and sensitive changes stay behind agreed approval gates.', outcomes: [['Fewer handoffs', 'Routine coordination follows an agreed sequence.'], ['Visible ownership', 'Know who owns the next decision.'], ['Recoverable work', 'Retries, stops and escalation paths are defined before launch.']], measures: ['End-to-end completion time', 'Manual touches per case', 'Exception resolution time', 'Cost per completed workflow'], faq: [['How much freedom does an agent have?', 'Only the tools, data, actions and budgets defined for its role. We agree what it can do automatically, what needs approval and when it must stop.'], ['What happens if a tool fails?', 'The workflow uses explicit retry limits and escalation rules. A failed step is recorded and routed instead of silently continuing.'], ['Can we start with one workflow?', 'Yes. One bounded workflow with a measurable baseline is usually the best starting point.']] },
    { slug: 'enterprise-knowledge-systems', name: 'Enterprise Knowledge', headline: 'Your knowledge. Within reach.', short: 'Useful answers from the information you already own.', description: 'Make policies, SOPs, contracts and past work easier to use. Answers come with their sources, respect access permissions and say when the evidence is missing.', uses: [['Policies & SOPs', 'Find the current process without asking around.'], ['Project knowledge', 'Reuse lessons, decisions and previous work.'], ['Sales & proposals', 'Find approved product and commercial information.'], ['Internal support', 'Help teams answer everyday questions from trusted sources.']], flow: [['Ask', 'A question from your team'], ['Check access', 'Use only permitted sources'], ['Retrieve', 'Find the relevant evidence'], ['Answer', 'Cite the source or flag a gap'], ['Improve', 'An owner reviews missing knowledge']], gate: 4, gateNote: 'Source owners review gaps and changes. Unsupported answers are withheld.', outcomes: [['Less searching', 'Bring the relevant material into the answer.'], ['Sources you can inspect', 'Open the evidence and check the context.'], ['Knowledge that stays useful', 'Give stale content and unanswered questions an owner.']], measures: ['Time to find an answer', 'Source-supported answer rate', 'Unanswered question rate', 'Active team adoption'], faq: [['Can it respect existing permissions?', 'Access rules are part of the design. We verify permissions during retrieval and test that restricted information stays restricted.'], ['What if the answer is not in our documents?', 'The system should say it cannot find enough evidence and route the gap to the appropriate owner.'], ['Who keeps the knowledge current?', 'Your source owners retain responsibility for the content. We design refresh schedules, version checks and review queues around them.']] },
    { slug: 'custom-ai-platforms', name: 'Custom AI Platforms', headline: 'Your way of working. Built into software.', short: 'A product shaped around your business.', description: 'Bring your data, workflows and AI capabilities into one purposeful platform. Give each role the tools it needs, with a foundation your team can maintain and extend.', uses: [['Internal workspaces', 'One place to work, review and track decisions.'], ['Customer & partner portals', 'Role-specific experiences built around a real service.'], ['Proprietary AI products', 'Turn a validated use case into a usable product.'], ['Connected capabilities', 'Share models, permissions and integrations across teams.']], flow: [['Frame', 'Users, workflow and success measures'], ['Design', 'Interfaces and system boundaries'], ['Build', 'Data, models and integrations'], ['Validate', 'People test the real workflow'], ['Operate', 'Monitor, maintain and improve']], gate: 3, gateNote: 'Your team signs off on quality, access and the release criteria before launch.', outcomes: [['A coherent product', 'The interface and underlying workflow work together.'], ['Reusable foundations', 'Build further use cases on shared capabilities.'], ['Clear ownership', 'Document the code, operations and support arrangements.']], measures: ['Task success rate', 'Active user adoption', 'Response time', 'Cost per completed task'], faq: [['When is a custom platform the right choice?', 'When your workflow needs cannot be met well by an existing product or a simpler integration. We validate that before recommending a build.'], ['Will we be tied to one AI vendor?', 'We design sensible separation between your product and its model providers. Portability and handover terms are agreed in the scope.'], ['What happens after launch?', 'Choose a managed operating arrangement or a documented handover. Either way, ownership, monitoring and support need to be explicit.']] },
    { slug: 'customer-workforce-ai', name: 'Customer & Workforce AI', headline: 'Be there for the everyday questions.', short: 'Help customers and teams get to the next step.', description: 'Handle enquiries, bookings and routine support with approved knowledge and connected workflows. Bring a person into the conversation when judgement, sensitivity or policy calls for it.', uses: [['Customer enquiries', 'Capture context and prepare relevant responses.'], ['Bookings & follow-ups', 'Coordinate the next step and keep a record.'], ['Workforce assistance', 'Help staff find information and complete routine tasks.'], ['Multilingual support', 'Test the languages and channels your audience uses.']], flow: [['Enquiry', 'A message or call arrives'], ['Understand', 'Capture intent and context'], ['Respond', 'Use approved information'], ['Escalate', 'A person handles sensitive cases'], ['Follow up', 'Record the outcome and next step']], gate: 3, gateNote: 'Sensitive conversations and commitments go to a person, with the context attached.', outcomes: [['More consistent responses', 'Every answer starts from approved information.'], ['Better handoffs', 'People pick up the conversation with context.'], ['Fewer forgotten follow-ups', 'The next step has a record and an owner.']], measures: ['Time to first useful response', 'Resolution rate', 'Escalation quality', 'Booking or follow-up completion'], faq: [['Can it work on WhatsApp or voice?', 'We scope the channels you need and the access they require. Channel provider charges and constraints are included in the operating plan.'], ['Will it make promises to customers?', 'Only within the rules and approved information you provide. Pricing exceptions, sensitive requests and commitments can require a person.'], ['Can our team take over?', 'Yes. Handover, conversation context and responsibility for the next response are designed into the workflow.']] },
    { slug: 'decision-intelligence', name: 'Decision Intelligence', headline: 'Know what changed. Decide what’s next.', short: 'Turn fragmented numbers into a clearer decision.', description: 'Connect your business data, agree the definitions and surface the changes that deserve attention. Give decision-makers the evidence, assumptions and context behind the numbers.', uses: [['Leadership reporting', 'A consistent view across teams, outlets or regions.'], ['Operational signals', 'Spot changes that warrant an investigation.'], ['Planning & scenarios', 'Compare assumptions and their possible effects.'], ['Performance reviews', 'Bring the source evidence into the discussion.']], flow: [['Connect', 'Bring approved data together'], ['Validate', 'Check freshness and definitions'], ['Analyse', 'Identify changes and possible drivers'], ['Review', 'People challenge the interpretation'], ['Decide', 'Record the action and owner']], gate: 3, gateNote: 'People make the decision. Forecasts and explanations expose their assumptions.', outcomes: [['Shared definitions', 'Agree what each metric means before comparing it.'], ['Less report preparation', 'Spend review time on the movement in the business.'], ['Decisions with context', 'See sources, caveats and the next action together.']], measures: ['Reporting preparation time', 'Data freshness', 'Reconciliation exceptions', 'Time from signal to action'], faq: [['Can it work with spreadsheets?', 'Yes, when the structure and update process are reliable enough. We assess source quality and may recommend cleaning up a few definitions first.'], ['Are forecasts guaranteed?', 'No. Forecasts are conditional estimates. The interface should show assumptions, uncertainty and the data period used.'], ['Will AI make business decisions for us?', 'The system supports the decision. Your authorised people remain responsible for interpreting the evidence and approving actions.']] },
    { slug: 'ai-infrastructure-governance', name: 'Infrastructure & Governance', headline: 'The confidence to keep it running.', short: 'See who can use it, what it did and what it costs.', description: 'Give AI systems an operating foundation: access controls, evaluations, logs, cost visibility and a clear response when something goes wrong. Core controls belong in every build.', uses: [['Access & permissions', 'Define who can see data and take each action.'], ['Evaluation & releases', 'Check changes against representative cases.'], ['Monitoring & costs', 'Track quality, reliability and usage together.'], ['Incident response', 'Give failures a recovery path and an owner.']], flow: [['Define', 'Policies, owners and boundaries'], ['Control', 'Permissions and runtime limits'], ['Evaluate', 'Quality, reliability and cost checks'], ['Approve', 'Authorise a production change'], ['Observe', 'Monitor and respond to incidents']], gate: 3, gateNote: 'Release owners approve changes against agreed checks, with a rollback path.', outcomes: [['Accountable access', 'A clear view of roles, permissions and actions.'], ['Safer changes', 'Evaluate new models and prompts before release.'], ['Visible operations', 'Review the system’s quality, usage and failures.']], measures: ['Evaluation pass rate', 'Incident recovery time', 'Cost per task', 'Access and audit coverage'], faq: [['Is governance a separate add-on?', 'Core permissions, approvals, logging and failure handling are included in how we build. This service also supports teams that need a broader shared operating foundation.'], ['Does this guarantee regulatory compliance?', 'No single platform guarantees compliance. We implement the agreed controls and evidence requirements with your security, legal and compliance owners.'], ['Can you review a system we already have?', 'Yes. We can assess the current architecture, controls and operating risks, then prioritise improvements.']] },
    { slug: 'website-design-development', name: 'Website Design & Development', headline: 'A website worthy of what you do.', short: 'Distinctive websites for brands, businesses and creators.', description: 'Bring your brand, story and business goals into one beautifully considered website. We shape the strategy, write the copy, design every page and build an experience that works from the smallest screen to the biggest opportunity.', uses: [['Brand websites', 'Make your identity, story and offer unmistakably yours.'], ['Business websites', 'Help visitors understand your services and take the next step.'], ['Creator websites', 'Give your work, audience and enquiries a home you own.'], ['Campaign & launch pages', 'Focus the message and guide attention to one clear action.']], flow: [['Discover', 'Audience, brand and business goals'], ['Shape', 'Sitemap, copy and user journeys'], ['Design', 'Visual direction and mobile layouts'], ['Review', 'Approve the complete experience'], ['Build & launch', 'Develop, check and publish']], gate: 3, gateNote: 'You review the design, copy and key journeys before the website goes live.', outcomes: [['A distinctive presence', 'A visual identity and page hierarchy that fit your brand.'], ['A clear next step', 'Purposeful content, navigation and calls to action.'], ['Built for everyday use', 'Responsive pages, accessible interactions and a practical handover.']], measures: ['Enquiry or conversion completion', 'Page loading performance', 'Mobile task completion', 'Search visibility and content engagement'], faq: [['Do you handle the copy as well?', 'Yes. We can develop the page structure and copy with you, from the main message to service details and calls to action. Final business claims and content are reviewed with your team.'], ['Will the website work on mobile?', 'Yes. Mobile layouts, navigation, touch controls and readable content are part of the build, not a separate afterthought.'], ['Can you redesign an existing website?', 'Yes. We review the current pages, keep valuable content and URLs where practical, and plan redirects for any structural changes.'], ['Can you connect forms, analytics or a CMS?', 'We scope the integrations and editing needs before the build. Any hosting, platform or third-party charges are made clear so you can choose what suits you.'], ['What happens after launch?', 'You receive the agreed handover and guidance. Ongoing updates, maintenance and content support can be scoped around your needs.']] }
];
export const solutions = [
    { id: 'enquiries', label: 'Enquiries', title: 'Keep every enquiry moving.', body: 'Capture the details, prepare a response and keep the follow-up on track.', steps: ['Enquiry', 'Qualify', 'Draft', 'Record', 'Follow up'], gate: 'Sensitive conversations go to a person.', service: 'customer-workforce-ai', name: 'An enquiry desk that follows through' },
    { id: 'documents', label: 'Documents', title: 'From incoming file to useful record.', body: 'Read the fields, check the details and route the exceptions with their evidence.', steps: ['Receive', 'Read', 'Validate', 'Review', 'Post'], gate: 'Unclear fields wait for review.', service: 'document-multimodal-intelligence', name: 'A document desk that checks its work' },
    { id: 'operations', label: 'Operations', title: 'Give every handoff a next step.', body: 'Coordinate repeatable work across teams and tools, with a visible owner for every decision.', steps: ['Trigger', 'Prepare', 'Check', 'Approve', 'Act'], gate: 'Consequential actions need approval.', service: 'agentic-operations', name: 'A clear path through back-office work' },
    { id: 'knowledge', label: 'Knowledge', title: 'Find the answer. See the source.', body: 'Make your approved knowledge available where your team asks questions.', steps: ['Ask', 'Check access', 'Find', 'Cite', 'Review gaps'], gate: 'Missing evidence is flagged, not filled in.', service: 'enterprise-knowledge-systems', name: 'Internal answers with evidence attached' },
    { id: 'reports', label: 'Reports', title: 'Spend less time building the numbers.', body: 'Connect your sources and show what changed, with consistent definitions and the evidence behind it.', steps: ['Connect', 'Validate', 'Compare', 'Review', 'Decide'], gate: 'People interpret the signal and decide.', service: 'decision-intelligence', name: 'A numbers pack ready for the discussion' },
    { id: 'specific', label: 'Something specific', title: 'Build around the way you work.', body: 'Turn a validated workflow into a product that fits your people, data and decisions.', steps: ['Frame', 'Design', 'Build', 'Validate', 'Operate'], gate: 'Your team approves the release.', service: 'custom-ai-platforms', name: 'A platform for the work only you do' },
    { id: 'websites', label: 'Websites', title: 'Make your first impression count.', body: 'A distinctive, mobile-ready website with a clear story and an easy next step.', steps: ['Discover', 'Write', 'Design', 'Review', 'Launch'], gate: 'Your brand, copy and journeys are reviewed before launch.', service: 'website-design-development', name: 'A website worthy of your brand' }
];
export const industries = [
    { name: 'Manufacturing & exporters', group: 'Operations', pain: 'Orders, specifications and paperwork move between disconnected teams.', uses: ['Read RFQs and purchase orders', 'Check supplier and shipping documents', 'Track exceptions and delivery signals'], measure: 'Order processing time', service: 'document-multimodal-intelligence' },
    { name: 'Logistics & 3PL', group: 'Operations', pain: 'Shipment updates and document checks interrupt the team all day.', uses: ['Match PODs and shipment records', 'Prepare claims with evidence', 'Flag delays and unanswered requests'], measure: 'Exception resolution time', service: 'agentic-operations' },
    { name: 'Professional services', group: 'Operations', pain: 'Experienced people spend too much time finding and reworking information.', uses: ['Search precedents with sources', 'Prepare document review packs', 'Coordinate proposals and delivery tasks'], measure: 'Time spent finding information', service: 'enterprise-knowledge-systems' },
    { name: 'Real estate & developers', group: 'High consideration', pain: 'Enquiries, availability and follow-ups live in different places.', uses: ['Qualify enquiries and book visits', 'Connect approved inventory information', 'Prepare booking and approval documents'], measure: 'Enquiry-to-visit progression', service: 'customer-workforce-ai' },
    { name: 'Healthcare & clinics', group: 'High consideration', pain: 'Front desks juggle appointments, paperwork and unanswered calls.', uses: ['Coordinate bookings and reminders', 'Check administrative document completeness', 'Review capacity and no-show patterns'], measure: 'Appointment completion rate', service: 'customer-workforce-ai' },
    { name: 'Education & lending', group: 'High consideration', pain: 'Seasonal demand overwhelms the team handling enquiries and applications.', uses: ['Route enquiries to a counsellor', 'Check application completeness', 'Track handoffs and cohort progress'], measure: 'Application turnaround time', service: 'document-multimodal-intelligence' },
    { name: 'D2C & e-commerce', group: 'Consumer', pain: 'Support, returns and stock questions compete for the same attention.', uses: ['Answer approved order-status questions', 'Route return and refund exceptions', 'Read product feedback for recurring issues'], measure: 'Resolution time per enquiry', service: 'customer-workforce-ai' },
    { name: 'Restaurants & hospitality', group: 'Consumer', pain: 'Peak-hour demand makes bookings, reviews and outlet reporting harder.', uses: ['Capture bookings and routine questions', 'Prepare review responses for approval', 'Compare outlet demand and cost signals'], measure: 'Bookings captured and completed', service: 'decision-intelligence' },
    { name: 'Multi-location retail', group: 'Consumer', pain: 'Local workarounds make it difficult to see a consistent business picture.', uses: ['Make SOPs available to store teams', 'Coordinate routine store requests', 'Compare like-for-like outlet measures'], measure: 'Reporting consistency across outlets', service: 'decision-intelligence' }
];
export const articles = [
    { slug: 'human-in-the-loop-product-decision', category: 'Operations', title: 'Design the human decision into the workflow.', excerpt: 'A useful approval is a product feature: the right person, the right evidence and a clear next step.', read: '5 min read', date: '2026-08-08', sections: [
            ['Start with the decision', '“A human will review it” is not enough of a design. Someone needs to know what they are deciding, why the work reached them and what will happen after they respond. Make that decision visible before connecting the first model.'],
            ['Define three paths', 'Let routine work proceed only inside agreed limits. Hold consequential actions for approval. Escalate questions that require specialist judgement or sit outside the system’s scope. These paths depend on the consequences of an error, the quality of the evidence and the reversibility of the action.'],
            ['Give the reviewer the evidence', 'Show the original request, relevant sources, proposed action and reason for escalation together. A reviewer should not have to repeat the investigation just to decide whether a suggestion is sound. Include what is missing and what the system could not establish.'],
            ['Design what happens while it waits', 'An approval queue needs an owner, a response expectation and a fallback. Decide what happens when the reviewer is unavailable, when a case becomes urgent or when the information changes before approval. An unanswered request should never disappear from view.'],
            ['Learn from corrections', 'Record whether the reviewer approved, edited or rejected the proposal, and why. Review patterns with the process owner. Use them to improve rules and evaluations; do not automatically turn every correction into training data or wider permissions.'],
            ['Make one gate concrete', 'Choose a recurring decision. Write down its trigger, authorised reviewer, required evidence, permitted responses and fallback. Walk through a normal case and a failure case with the person who will use it. That conversation often reveals more than another model demo.']
        ], takeaway: 'An approval should make a decision easier to make, easier to explain and easier to trace.', checklist: ['A named reviewer', 'The original evidence', 'A clear proposed action', 'Approve, edit or reject', 'A timeout and fallback', 'A record of the outcome'] },
    { slug: 'rank-ai-opportunities', category: 'Framework', title: 'Choose the first workflow with a clear head.', excerpt: 'Compare impact, repetition, readiness and risk before you commit a team and a budget.', read: '5 min read', date: '2026-08-05', sections: [
            ['Start with the work, not the tool', 'List five recurring workflows that lose time or create rework. Describe each from its trigger to its final outcome. Keep the unit of work concrete: a supplier invoice, a customer enquiry or a weekly report. A broad ambition such as “transform operations” is too vague to evaluate.'],
            ['Compare four dimensions', 'Impact asks what the delay or error costs the business. Repetition asks how often the work occurs. Readiness asks whether you can access representative inputs and name an owner. Risk asks what happens if the system is wrong. Discuss all four together instead of letting a single impressive score decide.'],
            ['Measure a real baseline', 'Observe representative cases. Record time spent, waiting time, number of handoffs and reasons for rework. Include difficult cases and ordinary ones. A useful baseline reflects the work the team actually does, including the exceptions that disappear from a polished process diagram.'],
            ['Find the smallest useful boundary', 'Choose a start and finish that your team can own. Reading an incoming file and preparing a review pack may be a useful first release even when final approval remains manual. Smaller boundaries make acceptance criteria easier to test and operating costs easier to understand.'],
            ['Check whether a simpler fix wins', 'A shared inbox rule, a clearer template or an existing integration may solve the problem. Compare that option with an AI build. The right starting point is the one that improves the work sustainably, with a level of complexity your team can support.'],
            ['Make the decision reviewable', 'Write a one-page case: the workflow, current baseline, proposed change, owner, required access, likely operating costs and stop conditions. Choose one candidate, or decide that more preparation is needed. A clear “not yet” is a useful result.']
        ], takeaway: 'Start where the work repeats, the evidence is available and the consequences can be controlled.', checklist: ['A specific recurring workflow', 'A measured current state', 'Representative examples', 'An accountable owner', 'A bounded first release', 'A simpler alternative considered'] },
    { slug: 'why-ai-pilots-fail', category: 'Field note', title: 'The demo is the easy part.', excerpt: 'A dependable system needs ownership, real-world evaluations and a plan for the cases that go wrong.', read: '5 min read', date: '2026-08-02', sections: [
            ['A demonstration answers a narrow question', 'A demo can show that a model handles an example. It does not yet show that the business can rely on it throughout a working week. Production introduces inconsistent inputs, unavailable tools, changed policies and people who do not follow the happy path.'],
            ['Test the awkward cases', 'Build an evaluation set from representative work: incomplete documents, ambiguous requests, duplicates and missing permissions. Write down the expected response. Sometimes the correct behaviour is to ask, stop or escalate. A confident answer is not automatically a successful one.'],
            ['Name the operating owner', 'A system needs someone accountable for the business outcome and someone responsible for its technical operation. Agree who reviews failures, updates source material and authorises changes. Make those responsibilities specific enough that the team knows who to call on an ordinary Tuesday.'],
            ['Make failure recoverable', 'Describe how the workflow behaves if an integration is unavailable, a response is late or a record is only partly updated. Set retry limits and protect against duplicate actions. Give operators a way to pause the workflow and understand what has already happened.'],
            ['Count the cost of the whole workflow', 'Model usage is only one part of operating cost. Include integrations, monitoring, human review, maintenance and the time spent correcting errors. Compare the completed workflow with its baseline, not the speed of a single model response.'],
            ['Launch with a feedback loop', 'Start within a controlled boundary. Review outcomes with the people doing the work and agree how changes are evaluated before release. Expand when the evidence supports it. A useful system gets better through steady attention after the first launch.']
        ], takeaway: 'Production readiness is a working agreement about quality, responsibility, cost and recovery.', checklist: ['Representative evaluation cases', 'Agreed acceptance criteria', 'Named business and technical owners', 'Approval and access rules', 'Failure and rollback procedures', 'A recurring operating review'] }
];
