import { ReferenceDocuments } from '@/components/studio/ReferencePages';
import { notFound, redirect } from 'next/navigation';
import { services } from '@/lib/redesign';
import { Hero, Section, Heading, Cards, Flow, FAQ, Closing, TextLink, Included } from '@/components/studio/Shared';
import { pageMetadata } from '@/lib/seo';
const legacy: Record<string, string> = { revenue: 'custom-ai-platforms', 'customer-experience': 'customer-workforce-ai', 'brand-intelligence': 'enterprise-knowledge-systems', 'business-operations': 'document-multimodal-intelligence' };
type Props = {
    params: Promise<{
        slug: string;
    }>;
};
export function generateStaticParams() { return [...services.map(s => ({ slug: s.slug })), ...Object.keys(legacy).map(slug => ({ slug }))]; }
export async function generateMetadata({ params }: Props) { const { slug } = await params; const s = services.find(s => s.slug === (legacy[slug] || slug)); return s ? pageMetadata({ title: s.name, description: s.description, path: `/systems/${s.slug}` }) : {}; }
export default async function Service({ params }: Props) { const { slug } = await params; if (legacy[slug])
    redirect(`/systems/${legacy[slug]}`); const s = services.find(s => s.slug === slug); if (!s)
    notFound(); if (slug === 'document-multimodal-intelligence') return <ReferenceDocuments />; const isWeb = slug === 'website-design-development'; return <><div className="container breadcrumb"><TextLink href="/systems">All services</TextLink></div><Hero label={s.name} title={s.headline} body={s.description} href={`/apply?system=${s.slug}`} primary={isWeb ? 'Discuss your website' : 'Discuss this system'} secondary={{ href: '#workflow', label: isWeb ? 'See the process' : 'See how it works' }} art={['enterprise-knowledge-systems', 'custom-ai-platforms', 'ai-infrastructure-governance'].includes(slug) ? 'knowledge' : 'flow'}/><Section light><Heading label="Where it fits" title={isWeb ? 'Your brand deserves its own space.' : 'Work that is ready for a clearer path.'}/><Cards items={s.uses}/></Section><Section id="workflow"><Heading label={isWeb ? 'From first idea to launch' : 'How it works'} title={isWeb ? 'Considered at every step.' : 'A clear path. A person where it matters.'}/><Flow steps={s.flow} gate={s.gate} note={s.gateNote}/></Section><Section light><Heading label="What changes" title={isWeb ? 'A better experience, from first impression onwards.' : 'Less friction in the work that matters.'}/><Cards items={s.outcomes}/></Section><Section><div className="split"><Heading label="What we measure" title="Make progress visible." body="Agree the measures before the work starts. Compare with the current state and review the evidence together."/><Included items={s.measures}/></div></Section>{isWeb && <Section light><Heading label="The whole website" title="Every page has a job to do."/><Cards items={[["Strategy & copy", "Audience, positioning, sitemap and clear page copy."], ["Visual & interaction design", "A distinctive direction with purposeful hierarchy and mobile layouts."], ["Development & launch", "Responsive implementation, metadata, forms and deployment."], ["Handover & ongoing care", "Editing guidance and support arrangements scoped around your team."]]}/></Section>}<FAQ items={s.faq}/><Closing title={isWeb ? 'Let’s make your next website.' : 'Bring us your version of this workflow.'} body={isWeb ? 'Tell us about your brand, your audience and where you want to go.' : 'We will map the work, the boundaries and the first useful step.'} href={`/apply?system=${s.slug}`} label={isWeb ? 'Discuss your website' : 'Discuss this system'}/></>; }
