export const finalServices = {
  'decision-intelligence': {name:'Decision Intelligence',art:'decision',title:'One business. One set of numbers.',body:'Bring reporting and business context together so your team can see what changed and decide what to do.',tabs:['Recurring reports','Outlet comparisons','Change detection','Scenario planning'],workflow:'From scattered data to a shared view.',steps:['Agree definitions','Connect sources','Check the data','Explain the change','Review the decision'],gate:'Assumptions stay visible. Recommendations remain separate from decisions.',outcomes:['Shared definitions','Traceable evidence','More useful reporting'],measures:['Preparation time','Detection time','Forecast error','Decision time'],faq:[['Are forecasts treated as facts?','No. Assumptions, uncertainty and the evidence behind the forecast remain visible.'],['What happens when data doesn’t match?','The difference is flagged for review. We agree definitions and reconciliation rules before reporting.'],['Who makes the final decision?','Your team. The system brings evidence and context together; the decision stays with the person you name.']],closing:'Bring us the report that takes too long to prepare.',support:['platform-outcomes','knowledge-outcomes','blueprint-investment']},
  'customer-workforce-ai': {name:'Customer & Workforce AI',art:'customer',title:'Good enquiries should not go cold.',body:'Handle routine questions and follow-ups while your people take care of sensitive conversations.',tabs:['Customer enquiries','Bookings','Service requests','Employee assistance'],workflow:'Keep the conversation moving.',steps:['Read the request','Find the right information','Prepare the response','Take permitted action','Route sensitive cases'],gate:'Unclear, sensitive or high-impact requests reach a trained person with context.',outcomes:['More consistent follow-up','Less repetitive handling','Clearer handovers'],measures:['First useful response','Resolution quality','Escalations','Review feedback'],faq:[['Can it make promises to customers?','Only within the rules you approve. Exceptions and commitments can require a person.']],closing:'Show us the conversations your team cannot keep up with.',support:['agentic-outcomes','knowledge-outcomes','about-tuesday']},
  'ai-infrastructure-governance': {name:'Infrastructure & Governance',art:'governance',title:'Know what it did. Control what happens next.',body:'Give your AI systems defined access, visible costs and a clear operating owner.',tabs:['Access control','Quality reviews','Operating visibility','Incident handling'],workflow:'Controls built into everyday operation.',steps:['Name the owners','Set permissions','Test quality','Monitor operation','Review changes'],gate:'New releases and high-impact actions follow the review rules your business agrees.',outcomes:['Visible ownership','Inspectable activity','Controlled change'],measures:['Quality checks','Access coverage','Running cost','Availability'],faq:[['Is governance a separate add-on?','Core operating controls belong with the systems we build. Wider infrastructure work is scoped to your needs.'],['How do permissions get managed?','We agree who can read, change and approve each part of the workflow, and review access as responsibilities change.'],['What happens when something goes wrong?','Failures are made visible and routed to a named owner, with agreed recovery and escalation steps.'],['Can we change the setup later?','Yes. Changes follow the review, testing and release process agreed for your system.']],closing:'Make the controls as clear as the workflow.',support:['platform-outcomes','agentic-outcomes','about-tuesday']},
} as const;
export type FinalServiceKey = keyof typeof finalServices;
export const finalArticles = [
 {slug:'human-in-the-loop-product-decision',category:'Operations',title:'Design the human decision into the workflow.',body:'A useful system knows when to act and when to ask.',excerpt:'Where automation should pause, what the reviewer needs and how to keep responsibility clear.',art:'human-hero'},
 {slug:'rank-ai-opportunities',category:'Frameworks',title:'Choose the first workflow with a clear head.',body:'The most impressive idea is not always the most useful place to start.',excerpt:'Compare value, frequency, readiness and risk before committing to a build.',art:'rank-hero'},
 {slug:'why-ai-pilots-fail',category:'Field notes',title:'The demo is the easy part.',body:'A convincing example becomes useful only when the whole workflow can support it.',excerpt:'Why reliable operation needs ownership, exception handling and a baseline.',art:'demo-hero'},
] as const;
