type Five = [string,string,string,string,string];
export type TabWorkflow = { title:string; example:string; steps:Five; details:Five; gate:string };
const w=(title:string,example:string,steps:Five,details:Five,gate:string):TabWorkflow=>({title,example,steps,details,gate});
export const tabWorkflows:Record<string,TabWorkflow[]> = {
 'document-multimodal-intelligence':[
  w('From invoice to a checked payable.','Invoice INV-1042 · ₹24,800',['Receive invoice','Extract supplier and totals','Match PO and receipt','Review discrepancies','Prepare payable record'],['Capture the invoice and its supplier reference.','Read tax, line items and the invoice total.','Compare billed quantities with the purchase order and goods receipt.','Send price, tax or quantity differences to accounts.','Prepare the approved payable for the accounting system.'],'Accounts reviews mismatches. Preparing a payable does not authorise payment.'),
  w('From purchase order to an approved commitment.','Purchase order PO-2086 · ₹72,000',['Capture purchase order','Read items and terms','Check budget and supplier','Obtain buyer approval','Record approved order'],['Receive the proposed order from the purchasing team.','Identify quantities, delivery dates and payment terms.','Check the approved supplier and available budget.','Route exceptions and spend commitments to the authorised buyer.','Record the approved order and its approval reference.'],'Orders outside agreed limits wait for the authorised buyer.'),
  w('From delivery note to a verified receipt.','Delivery DEL-3018 · 48 units',['Receive delivery note','Read quantities and signature','Match expected shipment','Resolve shortages or damage','Update goods receipt'],['Capture the delivery note and shipment reference.','Read delivered quantities and proof of receipt.','Compare the note with the expected shipment.','Show missing units, damage or signatures to the delivery reviewer.','Prepare the accepted goods receipt for the stock record.'],'Missing signatures and quantity differences require delivery review.'),
  w('From customer documents to a complete file.','Customer CUS-4052 · 3 of 4 records',['Collect customer documents','Identify required records','Check completeness and expiry','Request missing information','Update verified customer file'],['Collect the records against the customer reference.','Classify each file against the required-document checklist.','Check that required fields are present and records are current.','Prepare a request for the missing fourth record.','Attach reviewed documents and their verification status.'],'Unclear customer records stay unverified until your team confirms them.'),
 ],
 'enterprise-knowledge-systems':[
  w('Find the policy that applies.','Expense approval policy',['Ask a policy question','Find the current policy','Check scope and effective date','Cite the applicable clause','Flag policy gaps'],['Ask which expense approval rule applies.','Retrieve the policy the employee is permitted to read.','Check the policy version and employee applicability.','Show the answer with its section and source text.','Identify missing or conflicting policy evidence.'],'Policy conflicts and missing evidence go to the policy owner.'),
  w('Find the approved way to do the work.','Supplier-change procedure',['Describe the operational task','Retrieve the approved SOP','Check prerequisites and version','Cite the procedure steps','Flag undocumented exceptions'],['Describe the supplier detail that needs changing.','Find the approved supplier-change procedure.','Check access, prerequisites and the latest revision.','Explain the procedure with a source citation.','Route cases not covered by the procedure to its owner.'],'An undocumented exception needs the process owner’s judgement.'),
  w('Trace a project decision to its source.','Project scope approval',['Ask about a project decision','Find permitted project records','Trace dates and approvals','Cite the decision record','Flag conflicting records'],['Ask who approved the scope.','Retrieve the project’s permitted decision records.','Check the decision date, approver and superseding changes.','Attach the relevant approval record to the answer.','Make absent or contradictory approvals visible.'],'Missing approval evidence is never treated as an approved decision.'),
  w('Find the right product information.','Current product specifications',['Identify product and version','Retrieve approved specifications','Check release and audience','Cite the product source','Flag obsolete information'],['Identify the product and version being discussed.','Retrieve the approved product handbook.','Check release status and who may see the specification.','Answer with the specification and version citation.','Flag archived or conflicting specifications.'],'Unreleased and restricted product information follows existing permissions.'),
 ],
 'agentic-operations':[
  w('Give every new starter a clear path.','New starter onboarding',['Capture starter details','Prepare onboarding checklist','Coordinate team tasks','Approve access requests','Record onboarding handover'],['Capture role, manager and start date.','Prepare the role-specific equipment and induction checklist.','Route equipment and induction tasks to IT and the team.','The manager reviews requested system access.','Record the approved handover and outstanding tasks.'],'Access waits for the named manager’s approval.'),
  w('Move an order from request to handover.','Order coordination request',['Capture order requirements','Check stock and capacity','Coordinate fulfilment','Approve delivery commitment','Record order handover'],['Capture requested items, quantities and delivery date.','Check available stock and fulfilment capacity.','Prepare tasks for sales, warehouse and delivery teams.','A person approves the customer-facing delivery commitment.','Record the agreed order handover and owners.'],'Delivery promises and substitutions require approval.'),
  w('Resolve a difference with its evidence.','Account reconciliation request',['Collect ledger and bank entries','Match transaction references','Identify unmatched amounts','Approve proposed adjustments','Record reconciliation outcome'],['Collect the permitted ledger and bank statement entries.','Match references, dates and amounts.','Group unmatched transactions with supporting evidence.','Finance reviews proposed adjustments before posting.','Record the approved reconciliation and unresolved items.'],'Adjustments never post without the authorised finance reviewer.'),
  w('Route recurring requests to the right owner.','Recurring facilities request',['Capture request and location','Classify priority and owner','Prepare the response task','Approve spend or changes','Record request resolution'],['Capture the maintenance request and affected location.','Assign the agreed priority and responsible team.','Prepare the permitted facilities task.','The owner approves spend or changes to the premises.','Record the resolution and requester handover.'],'Spending and sensitive changes wait for the assigned owner.'),
 ],
 'custom-ai-platforms':[
  w('Build a workspace around your team.','Internal task workspace',['Map team roles and tasks','Design the work queue','Connect internal records','Test role-based journeys','Launch with team ownership'],['Identify team roles and their recurring tasks.','Define queue states, handoffs and permissions.','Map approved internal records to the work queue.','Test restricted access and exception handling by role.','Agree the team owner and support process.'],'Internal records remain available only to authorised roles.'),
  w('Give customers a clear place to act.','Customer self-service portal',['Map the customer journey','Design account and request views','Connect customer-specific data','Test identity and isolation','Launch with customer support'],['Identify what customers need to view and request.','Define account, request and progress screens.','Map each customer to only their permitted records.','Test sign-in, account separation and failed requests.','Agree support ownership and customer guidance.'],'Customer data isolation must pass review before release.'),
  w('Build a tool for the specialist’s task.','Specialist quoting tool',['Define the expert task','Design inputs and controls','Connect rules and evidence','Validate with expert cases','Release to approved specialists'],['Identify the quoting task and expert decisions.','Define required inputs and editable assumptions.','Connect approved pricing rules and source evidence.','Have specialists review representative and edge cases.','Agree the trained users, release criteria and updates.'],'Expert judgement and exceptional quotes stay with the specialist.'),
  w('Connect the operation in one platform.','Multi-team operations platform',['Map operational handoffs','Design queues and approvals','Connect business systems','Test end-to-end recovery','Launch with operating controls'],['Map teams, handoffs and operational ownership.','Define task queues, states and approval boundaries.','Connect approved business-system interfaces.','Test normal work, integration failures and recovery.','Agree monitoring, incident ownership and rollback.'],'Cross-system writes and releases follow agreed approval rules.'),
 ],
 'decision-intelligence':[
  w('Turn recurring reporting into a shared view.','Weekly sales report',['Agree report definitions','Collect period data','Reconcile totals','Explain weekly changes','Review and publish report'],['Agree revenue, returns and reporting cut-off definitions.','Collect the week’s approved sales and returns records.','Reconcile source totals and highlight missing records.','Explain changes with source-linked evidence.','The report owner reviews the pack before circulation.'],'Unreconciled figures stay flagged until the report owner reviews them.'),
  w('Compare outlets on the same basis.','Monthly outlet comparison',['Choose comparable outlets','Align periods and measures','Adjust for trading differences','Compare outlet performance','Review local context'],['Select outlets and the reporting month.','Use consistent sales, cost and trading-day definitions.','Show closures, opening dates and other comparability limits.','Compare outcomes with supporting outlet records.','Managers review local context before deciding what to change.'],'Outlet rankings show comparability limits and require local context.'),
  w('Spot a change and understand its cause.','Unexpected margin movement',['Set a baseline and threshold','Monitor incoming measures','Check the anomaly','Investigate likely drivers','Review the alert'],['Agree the usual margin range and alert threshold.','Compare current measures against that baseline.','Check whether the change comes from missing or delayed data.','Inspect price, cost and product-mix evidence.','The business owner reviews the evidence and response.'],'An alert identifies a change; it does not prove its cause.'),
  w('Explore a scenario before making a decision.','Pricing scenario comparison',['Define the business question','Set scenario assumptions','Calculate possible outcomes','Compare sensitivity and risk','Review the decision'],['Frame the pricing decision and comparison period.','Enter explicit demand, price and cost assumptions.','Calculate illustrative outcomes under each assumption set.','Show which assumptions most affect the outcome.','Decision-makers review uncertainty before choosing a course.'],'Scenarios are conditional estimates, not forecasts presented as facts.'),
 ],
 'customer-workforce-ai':[
  w('Keep a promising enquiry moving.','New product enquiry',['Capture enquiry and intent','Find approved product information','Prepare a relevant reply','Record the lead and follow-up','Hand over sensitive questions'],['Capture what the prospect is asking and their contact context.','Retrieve permitted product details and current terms.','Prepare an answer using those approved sources.','Record the lead and a permitted follow-up task.','Route negotiation or sensitive questions to the sales team.'],'Pricing exceptions and customer commitments require a person.'),
  w('Take a booking from request to confirmation.','Appointment booking request',['Capture booking preferences','Check available slots','Offer permitted options','Confirm the selected slot','Route booking exceptions'],['Capture service, date and timing preferences.','Check the connected calendar for available slots.','Offer only slots and terms allowed by the booking rules.','Recheck availability before recording the selected appointment.','Send overbooking, cancellation or special requests to staff.'],'Confirmation follows availability checks; exceptions go to the booking team.'),
  w('Give a service request a clear next step.','Customer support request',['Capture issue and order reference','Retrieve service history','Suggest an approved resolution','Update the support ticket','Escalate unresolved issues'],['Capture the problem and relevant order or account reference.','Retrieve permitted order details and previous support activity.','Prepare the resolution allowed by the support policy.','Record the response and next action on the ticket.','Hand unresolved or high-impact cases to a trained reviewer.'],'Refund exceptions and sensitive complaints stay with your support team.'),
  w('Help employees find the right assistance.','Employee leave-policy question',['Identify the employee request','Check access and policy','Prepare a source-based answer','Route the internal request','Hand confidential cases to HR'],['Identify whether the employee needs information or an action.','Check the employee’s permitted policy sources.','Prepare an answer with the applicable policy reference.','Create the permitted HR or IT request for the right owner.','Route personal, confidential or exceptional matters to HR.'],'Personal employment decisions and confidential cases require HR.'),
 ],
 'ai-infrastructure-governance':[
  w('Make access match responsibility.','New team-member access request',['Identify user and owner','Map required permissions','Review least-privilege access','Apply approved permissions','Schedule access review'],['Identify the user, role and approving owner.','Map the minimum records and actions needed for the role.','Check that proposed access excludes unnecessary permissions.','Apply only the access the owner has approved.','Record the approval and next review date.'],'Permission changes require the authorised access owner.'),
  w('Review quality against real work.','Monthly system quality review',['Choose representative cases','Run agreed quality checks','Inspect failures and corrections','Approve remedial changes','Recheck quality after changes'],['Select normal cases and known exceptions.','Evaluate outputs against agreed acceptance criteria.','Show failures and reviewer corrections with evidence.','The quality owner approves proposed remediation.','Repeat relevant checks before releasing the change.'],'Failed acceptance checks remain visible and can block release.'),
  w('See how the system is operating.','Weekly operating health review',['Collect run and cost records','Check availability and usage','Flag cost or failure changes','Assign follow-up ownership','Review operating trends'],['Collect permitted run logs, availability and cost records.','Compare operation with agreed service expectations.','Flag unusual errors, usage or spending.','Assign each follow-up to a named operating owner.','Review trends and record the agreed actions.'],'Operating alerts trigger review within agreed access and spending limits.'),
  w('Give an incident a controlled response.','Failed integration incident',['Detect and classify incident','Notify the response owner','Contain affected actions','Recover and verify service','Record the incident review'],['Identify the failed integration and affected work.','Notify the named responder with impact and evidence.','Pause affected actions using the agreed containment rules.','Restore the integration and verify representative cases.','Record the cause, resolution and preventive follow-up.'],'Recovery, rollback and high-impact actions follow the incident approval rules.'),
 ],
};
