'use client';

import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, ArrowRight, Monitor, Smartphone, ShoppingBag, Check, Plus, ChevronRight, ArrowDown, X, Sparkles, MousePointer2 } from 'lucide-react';
import './website-cinema.css';

const concepts = [
  {id:'shop',label:'Commerce',brand:'FORME',tag:'A daily ritual. An extraordinary store.',description:'A premium Indian D2C storefront, with considered product discovery, rupee pricing and a delivery-pincode journey.',features:['Product discovery','Delivery pincodes','Shopping bag'],hint:'Choose a ritual. Check a pincode. Try the bag.',audience:'Brand / online store',image:'shop'},
  {id:'restaurant',label:'Hospitality',brand:'EMBER',tag:'Make the table feel worth booking.',description:'A contemporary Bengaluru dining concept, from a seasonal Indian menu to a direct table enquiry.',features:['Menu exploration','Reservation journey','Mobile discovery'],hint:'Explore the menu. Prepare a table request.',audience:'Restaurant / hospitality',image:'restaurant'},
  {id:'creator',label:'Creators',brand:'MIRA / FIELD NOTES',tag:'A world that could only be yours.',description:'An independent Indian creator’s home for editorial work, brand collaborations and a direct audience relationship.',features:['Editorial stories','Portfolio discovery','Audience signup'],hint:'Change the journal category. Open a story.',audience:'Creator / personal brand',image:'creator'},
  {id:'property',label:'Real estate',brand:'STILL HOUSE',tag:'Sell the feeling of being there.',description:'A boutique residence concept for Goa: architecture, considered details and a personal viewing enquiry.',features:['Property details','Gallery views','Visit enquiry'],hint:'Explore the residence. Request a viewing.',audience:'Property / architecture',image:'property'},
  {id:'saas',label:'SaaS & products',brand:'RELAY',tag:'Let people experience the product.',description:'A product experience for an Indian software business serving teams here and around the world.',features:['Interactive product','Pricing comparison','Product-led storytelling'],hint:'Move a task forward. Compare billing options.',audience:'SaaS / digital product',image:'consulting'},
  {id:'advisory',label:'Services',brand:'NORTH / ADVISORY',tag:'Make expertise easy to understand.',description:'A premium advisory concept for India’s founder-led businesses, connecting ambition to a practical engagement.',features:['Service discovery','Clear positioning','Qualified enquiries'],hint:'Choose a business challenge to see the approach.',audience:'Business / professional services',image:'consulting'},
] as const;
type ConceptId = typeof concepts[number]['id'];
const photo = (name:string) => `/images/web-${name}.webp`;

function CommerceDemo(){
  const [ritual,setRitual]=useState(0);const [bag,setBag]=useState(0);const [open,setOpen]=useState(false);const [pincode,setPincode]=useState('');const [delivery,setDelivery]=useState('');
  const products=[{name:'The morning ritual',note:'A gentle start. A brighter day.',price:1800},{name:'The evening reset',note:'Slow down. Let the day go.',price:2200}];const p=products[ritual];
  return <div className="wc-shop"><nav className="wc-demo-nav"><strong>FORME<span>SKIN, CONSIDERED.</span></strong><span>Bengaluru / Everyday essentials</span><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={`Shopping bag, ${bag} items`}><ShoppingBag size={18}/>{bag}</button></nav><div className="wc-shop-body"><div className="wc-shop-photo"><Image src={photo('shop')} alt="Considered skincare product still life" width={933} height={1400} sizes="(max-width: 760px) 100vw, 50vw"/><span>LESS, BUT BETTER.</span></div><div className="wc-shop-copy"><small>ESSENTIALS / 01</small><h3>A little ritual.<br/><em>A lot of you.</em></h3><p>Skincare for city mornings, humid evenings and the moments you make your own.</p><div className="wc-rituals" role="group" aria-label="Choose a skincare ritual">{products.map((v,i)=><button key={v.name} aria-pressed={i===ritual} onClick={()=>setRitual(i)}>{i===0?'AM / Morning':'PM / Evening'}</button>)}</div><h4>{p.name}</h4><p>{p.note}</p><button className="wc-demo-button" onClick={()=>{setBag(b=>b+1);setOpen(true)}}>Add ritual <span>₹{p.price.toLocaleString('en-IN')}</span></button><form className="wc-delivery" onSubmit={e=>{e.preventDefault();const cities:Record<string,string>={'560038':'Bengaluru','400050':'Mumbai','110003':'New Delhi'};setDelivery(cities[pincode]?`${cities[pincode]}: sample delivery estimate, 2–4 working days.`:'This concept has no delivery rule for that pincode. Try a sample below.')}}><label htmlFor="wc-pincode">Delivery pincode</label><div><input id="wc-pincode" value={pincode} onChange={e=>{setPincode(e.target.value.replace(/\D/g,'').slice(0,6));setDelivery('')}} inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required placeholder="560038"/><button>Check</button></div><small>Sample: 560038 · 400050 · 110003</small><p role="status">{delivery}</p></form><small>Concept store · no payment or order is taken</small></div></div>{open&&<div className="wc-demo-reveal" role="status"><ShoppingBag size={18}/><span>{bag?`${bag} ${bag===1?'ritual':'rituals'} in your demo bag.`:'Your demo bag is empty.'}</span>{bag>0&&<button onClick={()=>setBag(0)}>Empty bag</button>}<button aria-label="Close shopping bag" onClick={()=>setOpen(false)}><X size={18}/></button></div>}</div>
}

function RestaurantDemo(){
  const [menu,setMenu]=useState('Signature');const [booking,setBooking]=useState(false);const [ready,setReady]=useState('');
  const dishes:Record<string,string[]>={Signature:['Pepper-roasted mushroom · ₹640','Smoked aubergine & millet · ₹780','Tender coconut & jaggery · ₹460'],'Plant-led':['Charred greens & sesame · ₹540','Roasted cauliflower & cashew · ₹720','Seasonal mango sorbet · ₹380']};
  function reserve(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setReady(`Table for ${f.get('guests')} at ${f.get('time')}. Demo request prepared; no reservation has been made.`)}
  return <div className="wc-restaurant"><nav className="wc-demo-nav"><strong>EMBER<span>CONTEMPORARY INDIAN</span></strong><span>Indiranagar, Bengaluru · concept</span><button onClick={()=>{setBooking(!booking);setReady('')}}>{booking?'Back to menu':'Find a table'}<ArrowUpRight size={16}/></button></nav><div className="wc-restaurant-scene"><Image src={photo('restaurant')} alt="Warm restaurant atmosphere and thoughtfully served food" width={1200} height={800} sizes="(max-width: 760px) 100vw, 80vw"/><div><small>GOOD EVENINGS START HERE</small><h3>Come for dinner.<br/><em>Stay for the feeling.</em></h3></div></div>{booking?<form className="wc-booking" onSubmit={reserve}><label>Guests<select name="guests"><option>2</option><option>4</option><option>6</option></select></label><label>Preferred time<select name="time"><option>7:00 PM</option><option>8:00 PM</option><option>9:00 PM</option></select></label><button className="wc-demo-button">Prepare request <ArrowRight size={16}/></button><p role="status">{ready||'Try the booking journey. This concept does not make reservations.'}</p></form>:<div className="wc-menu"><div><small>FROM THE KITCHEN</small><div role="group" aria-label="Restaurant menu">{Object.keys(dishes).map(k=><button key={k} aria-pressed={menu===k} onClick={()=>setMenu(k)}>{k}</button>)}</div></div><ul>{dishes[menu].map(d=><li key={d}>{d}</li>)}</ul></div>}</div>
}

function CreatorDemo(){
  const [category,setCategory]=useState('Travel');const [story,setStory]=useState(false);const [subscribed,setSubscribed]=useState(false);
  const stories:Record<string,{title:string;body:string}>={Travel:{title:'A weekend beyond the city.',body:'A drive into the Western Ghats. Coffee before the trail. Notes on travelling slowly, close to home, and finding stories beyond the obvious stops.'},Design:{title:'Finding a quieter kind of beautiful.',body:'Independent studios, thoughtful spaces and objects made with a point of view. A personal edit of contemporary design across India.'},Life:{title:'Notes from an ordinary Sunday.',body:'Coffee before the inbox. A long walk without a destination. Small rituals are often the ones that stay with us.'}};
  return <div className="wc-creator"><nav className="wc-demo-nav"><strong>MIRA / FIELD NOTES</strong><span>Stories. Places. A point of view.</span></nav><div className="wc-creator-grid"><div><small>INDIA, THROUGH A PERSONAL LENS</small><h3>A life<br/>less <em>ordinary.</em></h3><p>Based in Bengaluru. Collecting places, independent design and stories from across India.</p><div className="wc-journal-tabs" role="group" aria-label="Journal category">{Object.keys(stories).map(k=><button aria-pressed={category===k} key={k} onClick={()=>{setCategory(k);setStory(false)}}>{k}</button>)}</div><button className="wc-story-link" onClick={()=>setStory(!story)} aria-expanded={story}>{stories[category].title}<ArrowUpRight size={22}/></button>{story&&<p className="wc-story-text">{stories[category].body}</p>}</div><figure><Image src={photo('creator')} alt="An Indian landscape from a travel journal" width={1100} height={825} sizes="(max-width: 760px) 100vw, 50vw"/><figcaption>FIELD NOTES / A SLOWER PERSPECTIVE</figcaption></figure></div><form className="wc-newsletter" onSubmit={e=>{e.preventDefault();setSubscribed(true)}}><label htmlFor="wc-creator-email">A letter, once in a while.</label><div><input id="wc-creator-email" type="email" placeholder="Your email address" required onChange={()=>setSubscribed(false)}/><button aria-label="Try newsletter signup"><ArrowRight size={20}/></button></div><small role="status">{subscribed?'Signup preview complete. Your email has not been saved.':'Demo newsletter · no email is collected'}</small></form></div>
}

function PropertyDemo(){
  const [view,setView]=useState('The residence');const [visit,setVisit]=useState(false);
  return <div className="wc-property"><nav className="wc-demo-nav"><strong>STILL HOUSE</strong><span>Architecture for living.</span><button onClick={()=>setVisit(!visit)}>Arrange a visit <ArrowUpRight size={16}/></button></nav><div className={`wc-property-image ${view==='The details'?'wc-property-detail':''}`}><Image src={photo('property')} alt="Contemporary villa courtyard and pool in Goa" width={1100} height={734} sizes="(max-width: 760px) 100vw, 80vw"/><div><small>GOA / A RESIDENCE CONCEPT</small><h3>Space to<br/><em>be yourself.</em></h3></div><span>01 / PRIVATE RESIDENCES</span></div><div className="wc-property-bottom"><div className="wc-journal-tabs" role="group" aria-label="Explore the residence">{['The residence','The details'].map(k=><button key={k} aria-pressed={view===k} onClick={()=>{setView(k);setVisit(false)}}>{k}</button>)}</div><p>{view==='The residence'?'3 bedrooms · Pool courtyard · Goa concept':'Natural stone · Floor-to-ceiling glazing · Open-plan living'}</p></div>{visit&&<div className="wc-demo-reveal" role="status"><span>A guided viewing, at your pace. In a finished site, this connects to your sales team’s availability.</span><button aria-label="Close viewing details" onClick={()=>setVisit(false)}><X size={18}/></button></div>}</div>
}

function SaaSDemo(){
  const [annual,setAnnual]=useState(true);const [tasks,setTasks]=useState([false,false,true]);const [details,setDetails]=useState(false);
  return <div className="wc-saas"><nav className="wc-demo-nav"><strong><span className="wc-relay-mark">↗</span> relay</strong><span>From Bengaluru. For teams everywhere.</span><button onClick={()=>setDetails(!details)} aria-expanded={details}>View plan <ArrowUpRight size={16}/></button></nav><div className="wc-saas-grid"><div><small>ONE CLEAR PLACE FOR YOUR WORK</small><h3>Big ideas.<br/><em>Meet done.</em></h3><p>Give every task a home, every project a next step, and your team a little breathing room.</p><div className="wc-billing" role="group" aria-label="Example billing period"><button aria-pressed={!annual} onClick={()=>setAnnual(false)}>Monthly</button><button aria-pressed={annual} onClick={()=>setAnnual(true)}>Yearly</button></div><div className="wc-price">₹{annual?'790':'990'}<small> / user / month{annual?' · billed yearly':''}</small></div>{details&&<p className="wc-plan-detail">Concept team plan: shared projects, task ownership and activity history. Illustrative pricing; no subscription is offered.</p>}</div><div className="wc-product-app"><div className="wc-app-heading"><strong>Launch workspace</strong><span>DEMO</span></div><p>THIS WEEK / {tasks.filter(Boolean).length} OF 3 DONE</p>{['Approve the new homepage','Review the launch copy','Review the GST invoice flow'].map((t,i)=><button key={t} className={tasks[i]?'wc-task-done':''} onClick={()=>setTasks(tasks.map((v,j)=>j===i?!v:v))} aria-pressed={tasks[i]}><span>{tasks[i]?<Check size={16}/>:<Plus size={16}/>}</span>{t}<small>{tasks[i]?'Done':'To do'}</small></button>)}<div className="wc-progress-track"><span style={{width:`${tasks.filter(Boolean).length/3*100}%`}}/></div><small>Click a task to move it forward.</small></div></div></div>
}

function AdvisoryDemo(){
  const [service,setService]=useState(0);const [enquiry,setEnquiry]=useState(false);
  const items=[['Find your direction','Strategy','Clarify the opportunity, choose priorities and build a practical plan.'],['Build your next chapter','Growth','Align your offer, market and operating model around the next stage.'],['Make change work','Transformation','Turn the plan into clear responsibilities, milestones and review points.']];
  return <div className="wc-advisory"><nav className="wc-demo-nav"><strong>NORTH<span>INDEPENDENT ADVISORY</span></strong><span>Bengaluru / Mumbai · concept</span><button onClick={()=>setEnquiry(!enquiry)}>Let’s talk <ArrowUpRight size={16}/></button></nav><div className="wc-advisory-grid"><div><small>FOR WHAT COMES NEXT</small><h3>Good decisions.<br/><em>Lasting direction.</em></h3><p>Independent perspective for India’s founder-led businesses, from the next market to the next generation.</p><div className="wc-advisory-options" role="group" aria-label="Business challenge">{items.map((v,i)=><button aria-pressed={service===i} onClick={()=>{setService(i);setEnquiry(false)}} key={v[1]}>{v[1]}<ChevronRight size={16}/></button>)}</div><div className="wc-advisory-result" aria-live="polite"><h4>{items[service][0]}</h4><p>{items[service][2]}</p></div></div><Image src={photo('consulting')} alt="Sculptural architectural lines in natural light" width={1200} height={800} sizes="(max-width: 760px) 100vw, 50vw"/></div>{enquiry&&<div className="wc-demo-reveal" role="status"><span>Start with your {items[service][1].toLowerCase()} challenge. This is where a real site would open a tailored enquiry.</span><button aria-label="Close enquiry preview" onClick={()=>setEnquiry(false)}><X size={18}/></button></div>}</div>
}

function ConceptDemo({id}:{id:ConceptId}){switch(id){case 'shop':return <CommerceDemo/>;case 'restaurant':return <RestaurantDemo/>;case 'creator':return <CreatorDemo/>;case 'property':return <PropertyDemo/>;case 'saas':return <SaaSDemo/>;case 'advisory':return <AdvisoryDemo/>}}

export function WebsiteCinema(){
  const [selected,setSelected]=useState<ConceptId>('shop');const [device,setDevice]=useState('desktop');const [audience,setAudience]=useState('Brand / online store');const [goal,setGoal]=useState('Sell products');const [features,setFeatures]=useState(['Brand & visual direction','Copy & page structure']);
  const concept=concepts.find(c=>c.id===selected)!;
  useEffect(()=>{function fromHash(){const match=concepts.find(c=>window.location.hash===`#concept-${c.id}`);if(!match)return;setSelected(match.id);setAudience(match.audience);document.getElementById('website-showcase')?.scrollIntoView({block:'start'})}fromHash();window.addEventListener('hashchange',fromHash);return()=>window.removeEventListener('hashchange',fromHash)},[]);
  const brief=`I would like a website for: ${audience}.\nPrimary goal: ${goal}.\nInterested in: ${features.length?features.join(', '):'Help defining the scope'}.\nDesign direction I explored: ${concept.brand} (${concept.label}).`;
  function toggleFeature(f:string){setFeatures(v=>v.includes(f)?v.filter(x=>x!==f):[...v,f])}
  return <div className="wc-page">
    <section className="wc-intro"><div className="container"><div className="wc-overline"><span>BYBO / WEBSITE STUDIO</span><span>INDIAN BUSINESSES · BRANDS · CREATORS</span></div><div className="wc-intro-grid"><div className="wc-intro-copy"><h1>Make them <br/>stop.<br/><em>Make them stay.</em></h1><p>For ambitious Indian businesses, brands and creators.<br/>Built to turn attention into action.</p><div className="actions"><a className="button" href="#website-showcase">Enter the showcase <ArrowDown size={18}/></a><a className="wc-quiet-link" href="#website-brief">Let’s build yours <ArrowUpRight size={18}/></a></div><div className="wc-intro-note"><span>01 — 06</span> Six worlds. Yours should be different, too.</div></div><div className="wc-cinema-wall" aria-label="A preview of three website design concepts">{[concepts[2],concepts[0],concepts[3]].map((c,i)=><a href="#website-showcase" className={`wc-film wc-film-${i}`} key={c.id} onClick={()=>setSelected(c.id)} aria-label={`Explore ${c.brand} ${c.label} concept`}><div className="wc-film-chrome"><span>BYBO CONCEPT / {String(i+1).padStart(2,'0')}</span><ArrowUpRight size={15}/></div><div className={`wc-film-cover wc-cover-${c.id}`}><Image src={photo(c.image)} alt="" width={1200} height={800} sizes="(max-width: 760px) 65vw, 38vw"/><strong>{c.brand}</strong><span>{c.id==='shop'?'A little ritual.\nA lot of you.':c.id==='creator'?'A life less\nordinary.':'Space to\nbe yourself.'}</span></div></a>)}</div></div><div className="wc-intro-footer"><span>STRATEGY</span><i>+</i><span>DESIGN</span><i>+</i><span>DEVELOPMENT</span><i>+</i><span>CARE</span><a href="#website-showcase">Scroll to experience <ArrowDown size={15}/></a></div></div></section>
    <section className="wc-showcase" id="website-showcase"><div className="container"><div className="wc-section-top"><div><p className="eyebrow">THE INTERACTIVE SHOWCASE</p><h2>One studio.<br/><em>Very different worlds.</em></h2></div><p>A store should feel like a store. A creator’s world should feel like theirs. Explore six contemporary Indian business concepts—and try what’s inside.</p></div><div className="wc-concept-tabs" role="group" aria-label="Website concept category">{concepts.map((c,i)=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}><span>0{i+1}</span>{c.label}</button>)}</div><div className="wc-stage-meta"><div><strong>{concept.brand}</strong><span>{concept.tag}</span></div><div className="wc-devices" role="group" aria-label="Preview device"><button aria-pressed={device==='desktop'} onClick={()=>setDevice('desktop')} aria-label="Desktop preview"><Monitor size={19}/><span>Desktop</span></button><button aria-pressed={device==='mobile'} onClick={()=>setDevice('mobile')} aria-label="Mobile preview"><Smartphone size={18}/><span>Mobile</span></button></div></div><div className="wc-stage-surround"><div className={`wc-browser ${device==='mobile'?'wc-browser-mobile':''}`}><div className="wc-browser-bar"><div aria-hidden="true"><i/><i/><i/></div><span>{concept.brand.toLowerCase().replaceAll(' / ','-')} / concept preview</span><span>BYBO</span></div><div className="wc-demo-screen"><ConceptDemo key={selected} id={selected}/></div></div></div><div className="wc-stage-caption"><p><MousePointer2 size={17}/>{concept.hint}</p><span>Fictional brands. Interactive concepts, not client work.</span></div><div className="wc-concept-story"><p>{concept.description}</p><ul>{concept.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><a href="#website-brief" onClick={()=>setAudience(concept.audience)}>Build in this direction <ArrowUpRight size={18}/></a></div></div></section>
    <section className="wc-craft"><div className="container"><p className="eyebrow">MORE THAN A FIRST IMPRESSION</p><div className="wc-craft-heading"><h2>The feeling gets<br/>them in.<br/><em>The thinking moves<br/>them forward.</em></h2><p>Every page has a purpose. Every interaction has a next step. We bring the story, design and build together around what your business needs the website to do.</p></div><div className="wc-craft-list">{[['01','A reason to stay','Positioning, copy and an unmistakable visual identity.'],['02','A clear next move','Product discovery, bookings, enquiries or your next subscriber.'],['03','A pleasure on any screen','Thoughtful mobile layouts, accessible controls and considered performance.'],['04','A site you can keep growing','Content editing, integrations and a handover built around your team.']].map(v=><div key={v[0]}><span>{v[0]}</span><h3>{v[1]}</h3><p>{v[2]}</p></div>)}</div></div></section>
    <section className="wc-brief" id="website-brief"><div className="container"><div className="wc-section-top"><div><p className="eyebrow">YOUR NEXT WEBSITE STARTS HERE</p><h2>Let’s make<br/><em>your kind of different.</em></h2></div><p>Give us a starting point. We’ll shape the scope, the experience and the right way to build it with you.</p></div><div className="wc-brief-grid"><div className="wc-brief-controls"><label>I’m building for<select value={audience} onChange={e=>setAudience(e.target.value)}>{concepts.map(c=><option key={c.id}>{c.audience}</option>)}</select></label><label>The website needs to<select value={goal} onChange={e=>setGoal(e.target.value)}>{['Sell products','Generate qualified enquiries','Get more bookings','Showcase my work','Grow my audience','Explain a digital product'].map(g=><option key={g}>{g}</option>)}</select></label><fieldset><legend>What should we explore?</legend>{['Brand & visual direction','Copy & page structure','Commerce & payments','Bookings & enquiries','CMS & content editing','Connections to your tools'].map(f=><label key={f}><input type="checkbox" checked={features.includes(f)} onChange={()=>toggleFeature(f)}/><span>{f}</span></label>)}</fieldset></div><div className="wc-brief-summary"><Sparkles size={28}/><small>YOUR STARTING POINT</small><h3>{audience.split(' / ')[0]}.<br/><em>Built around you.</em></h3><dl><div><dt>The goal</dt><dd>{goal}</dd></div><div><dt>The direction</dt><dd>{concept.brand} / {concept.label}</dd></div><div><dt>The scope</dt><dd>{features.length?features.join(' · '):'Let’s define it together.'}</dd></div></dl><Link className="button" href={`/apply?system=website-design-development&message=${encodeURIComponent(brief)}`}>Discuss this website <ArrowUpRight size={18}/></Link><p>Your selections travel with you to the enquiry form.</p></div></div></div></section>
    <section className="wc-process"><div className="container"><div><p className="eyebrow">FROM IDEA TO LIVE</p><h2>One team.<br/>The whole picture.</h2></div><ol>{[['Discover','Your audience, goals, content and the job each page needs to do.'],['Art-direct','A distinctive visual direction, real copy and responsive page designs.'],['Build & refine','Working interactions, content tools and integrations, tested together.'],['Launch & care','Launch checks, editing guidance and an agreed plan for ongoing support.']].map((v,i)=><li key={v[0]}><span>0{i+1}</span><div><h3>{v[0]}</h3><p>{v[1]}</p></div></li>)}</ol></div></section>
    <section className="wc-faq"><div className="container"><h2>A few useful answers.</h2><div>{[['Are these websites real client projects?','These are fictional concept websites created to let you explore different design directions and interactions. They are not client projects or finished commerce, booking or subscription services.'],['Can you redesign our existing website?','Yes. We can work from your current site, content and brand, then agree what to retain, improve or rebuild. Redirects and continuity are part of the launch scope.'],['Can you connect bookings, payments or our existing tools?','Yes. We scope the integrations around your systems and the experience you need. Platform subscriptions, payment-provider charges and ongoing costs are made clear before the build.'],['How much will it cost, and how long will it take?','That depends on the pages, content, functionality and integrations. We agree the deliverables, fee and schedule after understanding your brief.'],['Will we be able to update the website?','We can include a content management setup and editing guidance for your team. Ongoing maintenance and improvements can be scoped separately.']].map(v=><details key={v[0]}><summary>{v[0]}<Plus size={20}/></summary><p>{v[1]}</p></details>)}</div></div></section>
    <section className="wc-finale"><div className="container"><span>YOUR NEXT CHAPTER, BY BYBO.</span><h2>Make your<br/><em>presence felt.</em></h2><a href="#website-brief" className="button">Let’s build something worth visiting <ArrowUpRight size={20}/></a></div></section>
  </div>
}
